name: journal
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  provider: ^6.0.5
  image_picker: ^0.8.6
  fluttertoast: ^8.1.2
  fast_immutable_collections: ^8.1.0
  modal_bottom_sheet: ^2.1.2
  shared_preferences: ^2.0.15
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  go_router: ^6.0.1
  rxdart: ^0.27.7
  flutter_slidable: ^2.0.0
  skeletons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
